server.port=${PORT:8085}

# RabbitMQ
spring.rabbitmq.addresses=${RABBITMQ_URL:amqp://guest:guest@localhost:5672}

# WebSocket
spring.websocket.allowed-origins=*

# Notification Queue
rabbitmq.exchange.notification=notification_exchange
rabbitmq.queue.notification=notification_queue
rabbitmq.routing.notification=notification.key

# Chat Queue
rabbitmq.exchange.chat=chat_exchange
rabbitmq.queue.chat=chat_queue
rabbitmq.routing.chat=chat.key
